name: CI - api-gateway
on:
  push:
    branches: [main]
    paths:
      - 'services/api-gateway/**'
      - 'common-dto/**'
  pull_request:
    paths:
      - 'services/api-gateway/**'
jobs:
  build-test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      service-path: services/api-gateway
