name: CI - card-service
on:
  push:
    paths:
      - 'services/card-service/**'
      - 'common-dto/**'
  pull_request:
    paths:
      - 'services/card-service/**'
jobs:
  build-test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      service-path: services/card-service
